language: php

php: 
  - 5.4
  - 5.5
  - 5.6

before_script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: 
  - phpunit
  - phpcs --standard=psr2 src
